### ISSUE TITLE
Macbook trackpad scrolling is wonky

### ISSUE THREAD

**Issue by rclai** [microsoft/monaco-editor#750]
This is happening with the demo editors on your project page.

Browser: Google Chrome

1. I can scroll to the right but I can't scroll to the left (after having scrolled to the right), the scroll event just bubbles up and triggers the back browser gesture

2. If I scroll up and down, it will occasionally get stuck, the scroll event bubbles up and also somehow triggers the back browser gesture. I believe this is because the vertical/horizontal detection logic is too strict. If you scroll just slightly 90 degrees off it will consider it horizontal scrolling, so you have to perfectly scroll vertically with your fingers or you'll be stuck.

Related: https://github.com/Microsoft/monaco-editor/issues/211

**Comment by mofux** [comment]
I am seeing the exact same behaviour on my Macbook. It is very annoying because you cannot scroll the editor content to the left - and even worse, it takes you back to the previous tab. I guess calling `evt.preventDefault()` on the `mousewheel` event listener should stop this from happing.

![kapture 2018-03-18 at 15 31 14](https://user-images.githubusercontent.com/2785983/37567118-6d8d7e50-2ac2-11e8-9b34-c0059f1768dd.gif)

**Comment by rclai** [comment]
@mofux thanks for the visual repro.

**Comment by jayspadie** [comment]
We've also had a few Mac users report this issue with our use of Monaco in VSTS recently (Chrome version 65.0.3325.181).  I see that a fix has been pushed out a couple of times (based on milestone changes).  If you have any information to share about the likelihood of it getting fixed anytime soon (if at all), that would be great.  Thanks.

**Comment by alexandrudima** [comment]
Number 2, specifically this part, from the OP is fixed in 0.12.0:

> I believe this is because the vertical/horizontal detection logic is too strict. If you scroll just slightly 90 degrees off it will consider it horizontal scrolling, so you have to perfectly scroll vertically with your fingers or you'll be stuck.

The commit that removed our massaging is https://github.com/Microsoft/vscode/commit/17959a75c3bade873d803e23aa7fb589d61a01e4#diff-f592f5d7367dc016da883a2dc3f89bfa and made its way to 0.12.0.

Now, to avoid going back... That is something an integrator can easily build. From my testing, browsers go back even if I scroll in a native `<textarea>`, so I don't plan to do anything to prevent going back via two fingers swipe on top of the editor. If you want to implement that for your website, it is IMHO doable on your side.

**Comment by spoenemann** [comment]
I still see scrolling problems with Firefox on Mac OS 10.13.4:
https://microsoft.github.io/monaco-editor/index.html

 * When I scroll up/down, the whole page scrolls in addition to the editor.
 * When "swipe between pages" is active in the system preferences and I scroll left/right in the monaco editor, nothing happens. If I scroll a bit more, the previous/next page is opened.

> Now, to avoid going back... That is something an integrator can easily build. From my testing, browsers go back even if I scroll in a native <textarea>, so I don't plan to do anything to prevent going back via two fingers swipe on top of the editor. If you want to implement that for your website, it is IMHO doable on your side.

@alexandrudima This is true when the editor has nothing to scroll, e.g. it is already at the leftmost position and I swipe further in that direction. But when the editor is scrolled to the right and I swipe to the right (i.e. scroll left), the editor should scroll and prevent the default action, which is to open the previous page.

It works fine with Safari and Chrome.

**Comment by rclai** [comment]
Yes, sorry I didn't specify that clearly. The problem is not being able to scroll to the left after having scrolled to the right.

**Comment by spoenemann** [comment]
I guess this depends on whether the browser renders any scroll bar for that DOM node, so it's a combination of the `overflow` property, the size of the node, and the size of its content.

AFAIK the only way to prevent "go back" programmatically is to call `preventDefault()` on the wheel event.

**Comment by Avinm** [comment]
The firefox vertical scroll bug mentioned by spoenemann, is major impairment to monaco's accessibility. Perhaps you could add an overflow:hidden attribute to the nearest parent element with a scrollbar while scrolling unless there are no more lines within monaco to scroll up/down? Or is it not possible to use the preventDefault?

**Comment by hross** [comment]
See [this VSTS issue](https://developercommunity.visualstudio.com/content/problem/310352/trackpad-scrolling-scrolls-the-wrong-direction-in.html) for related scrolling issues (reproducible in monaco playground):

**Comment by jayspadie** [comment]
This thread is specific to scrolling issues on MacBook, so I have created a separate issue to track the SurfaceBook PTP Edge 2-finger scrolling issue referenced above.  #1057 
> See this VSTS issue for related scrolling issues (reproducible in monaco playground):

**Comment by Nikolsi** [comment]
Hello 
Is there any quick fix for that?

Mac OS X 10.13.6
Chrome Version 71.0.3578.98 (64-bit)

**Comment by huangyingjie** [comment]
hey guys, how do you fix this problem? why is this issue still open? @rclai @spoenemann  @hross

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/vscode/commit/185d71b615e529b154c76907764bfda9270cb42f
